### ISSUE TITLE
在干净的 python 环境安装 fishbase 报错找不到 dateutil

### ISSUE THREAD

**Issue by wingfish** [chinapnr/fishbase#55]
在一个完全干净的 python 环境安装 fishbase 出错，比较奇怪。

Collecting fishbase
  Downloading https://files.pythonhosted.org/packages/a4/2b/45c42409bbb090cb5df5fbabda0b13189402070d00174f06755c51839d25/fishbase-1.0.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/y5/rt54swp16rvg9q5vfsdwp9jr0000gn/T/pip-install-n1alx_0y/fishbase/setup.py", line 3, in <module>
        from fishbase import __version__
      File "/private/var/folders/y5/rt54swp16rvg9q5vfsdwp9jr0000gn/T/pip-install-n1alx_0y/fishbase/fishbase/__init__.py", line 21, in <module>
        from .fish_date import *
      File "/private/var/folders/y5/rt54swp16rvg9q5vfsdwp9jr0000gn/T/pip-install-n1alx_0y/fishbase/fishbase/fish_date.py", line 4, in <module>
        from dateutil.relativedelta import relativedelta
    ModuleNotFoundError: No module named 'dateutil'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/y5/rt54swp16rvg9q5vfsdwp9jr0000gn/T/pip-install-n1alx_0y/fishbase/

---

在 setup.py 中是有 
>install_requires=['python-dateutil']

应该会自动安装 python-dateutil，也就是 dateutil

需要验证是否哪里有问题

**Comment by iTaa** [comment]
这个问题是由于在setup.py中 `from fishbase import __version__` 导致的, version的导入可使用正则的方式来提取，参考如下：
```python
import io
import re
with io.open('fishbase/__init__.py', 'rt', encoding='utf8') as f:
    version = re.search(r'__version__ = \'(.*?)\'', f.read()).group(1)
```
